Feature/ch160563
CartoDB/carto-react-template pull request #239
Opened 2021-06-14 08:52 UTC by aaranadev

2021-06-16 06:35 UTC, alasarr commented
Please, add a title at the PR, it's a public repo and the link to CH is not enough.

2021-06-16 06:35 UTC, alasarr commented
A description is also welcome

2021-06-16 06:36 UTC, alasarr commented on template-skeleton/template/src/App.js
> +  app: {
More than the target of this PR

2021-06-16 06:36 UTC, alasarr commented on template-skeleton/template/src/components/common/ErrorSnackbar.js
> +import { Snackbar } from '@material-ui/core';
It exceeds the feature scope of the PR

2021-06-16 06:37 UTC, alasarr commented on template-skeleton/template/src/components/common/Header.js
> +import { ReactComponent as CartoLogo } from 'assets/img/carto-logo.svg';
Ditto

2021-06-16 06:37 UTC, alasarr commented on template-skeleton/template/src/components/common/Header.js
> +      color: theme.palette.appBar?.contrastText || theme.palette.primary?.contrastText,
ditto

2021-06-16 06:38 UTC, alasarr commented on template-skeleton/template/src/components/common/Header.js
> +    <Hidden xsDown>
ditto

2021-06-16 06:39 UTC, alasarr commented on template-skeleton/template/src/components/layers/index.js
> +export default function getLayers() {
ditto

2021-06-16 06:41 UTC, alasarr requested changes
This PR exceeds the feature specified in the description: styles, new components, etc.

Add only in this PR the feature of destructuring props.

2021-06-16 06:55 UTC, aaranadev commented
@alasarr I leaved a note in the task: https://app.clubhouse.io/cartoteam/story/160574/improve-the-css-by-default-including-names-and-theme-file.

I've modified the files and the styles, I can't change the style only in other PR without conficts

2021-06-16 07:09 UTC, alasarr commented
>I've modified the files and the styles, I can't change the style only in other PR without conflicts

Create the style PR from this one. And add a note that this PR needs to be merged before

2021-06-16 07:13 UTC, aaranadev commented
Perfect

2021-06-16 07:13 UTC, alasarr commented
Steps:

1. Create a PR with only the features of this.
2. Create another PR with the improvement of styles and explain in the title and description what you're doing

2021-06-21 09:23 UTC, aaranadev commented
I've created several PR from this with minor improvements.

I close this PR

2021-06-21 09:23 UTC, closed without merging